<?php

namespace Inferno\DoctrineProxies\__CG__\GC\Unit\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UnitCombatSetting extends \GC\Unit\Model\UnitCombatSetting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'unitCombatId', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'distribution', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'attackPower', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'sourceUnit', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'targetUnit'];
        }

        return ['__isInitialized__', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'unitCombatId', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'distribution', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'attackPower', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'sourceUnit', '' . "\0" . 'GC\\Unit\\Model\\UnitCombatSetting' . "\0" . 'targetUnit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UnitCombatSetting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUnitCombatId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUnitCombatId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitCombatId', []);

        return parent::getUnitCombatId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDistribution(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistribution', []);

        return parent::getDistribution();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistribution(int $distribution): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistribution', [$distribution]);

        parent::setDistribution($distribution);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttackPower(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttackPower', []);

        return parent::getAttackPower();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttackPower(string $attackPower): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttackPower', [$attackPower]);

        parent::setAttackPower($attackPower);
    }

    /**
     * {@inheritDoc}
     */
    public function getSourceUnit(): \GC\Unit\Model\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourceUnit', []);

        return parent::getSourceUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setSourceUnit(\GC\Unit\Model\Unit $sourceUnit): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSourceUnit', [$sourceUnit]);

        parent::setSourceUnit($sourceUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTargetUnit(): \GC\Unit\Model\Unit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargetUnit', []);

        return parent::getTargetUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setTargetUnit(\GC\Unit\Model\Unit $targetUnit): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTargetUnit', [$targetUnit]);

        parent::setTargetUnit($targetUnit);
    }

}
